export const T = {
  ru: {
    join:'🎾 Подать заявку', apply:'🎾 Подать заявку', website:'🌐 Сайт PTF', about:'ℹ️ О PTF', how:'🏆 Как работает лига', yearly:'⭐ Yearly Race', pass:'🎟 League Pass', contact:'💬 Связаться', back:'⬅️ Назад', main_menu:'🏠 Главное меню', close_chat:'❌ Закрыть чат',
    help_user:'<b>Помощь</b>\n\nИспользуйте меню, чтобы подать заявку, посмотреть сайт, прочитать краткое объяснение лиги или связаться с организатором.',
    contact_prompt:'<b>💬 Чат с организатором открыт</b>\n\nНапишите ваш вопрос. Все следующие сообщения будут отправляться организатору, пока вы не закроете чат или не вернётесь в главное меню.', contact_sent:'✅ Сообщение отправлено организатору. Вы можете написать ещё одно сообщение прямо сюда или закрыть чат.', contact_closed:'✅ Чат с организатором закрыт.', cancelled:'Отменено.',
    application_received:'<b>Заявка получена!</b> 🎾\n\nТеперь выберите способ оплаты League Pass. После оплаты загрузите скриншот подтверждения.\n\nЕсли мест в сезоне не хватит или дивизион не будет подтверждён, Phuket Tennis Family вернёт оплату в полном размере.',
    pay_later:'⏳ Оплачу позже', bank:'🏦 Bank Transfer', crypto:'💵 USDT', call_admin:'💬 Связаться с организатором', choose_payment:'Выберите способ оплаты:', choose_crypto_network:'Выберите сеть USDT:', payment_later:'Окей. Вы можете оплатить позже. Организатор сможет сделать follow-up по вашей заявке.', send_proof:'После оплаты отправьте сюда скриншот подтверждения.', proof_received:'✅ Скриншот оплаты получен. Организатор проверит оплату и отдельно подтвердит ваш статус участия.',
    waitlist:'<b>Вы добавлены в waitlist.</b> ⏳\n\nМы сейчас определяем доступные места и финальный состав дивизионов. Приоритет получают игроки, которые уже имеют опыт участия в системе Phuket Tennis Family.\n\nМы сообщим вам, как только статус заявки изменится.', active:'<b>Поздравляем!</b> 🎾\n\nВаше участие подтверждено.', refunded:'<b>Refund</b>\n\nЕсли вы не попали в сезон из-за ограниченного количества мест или распределения дивизионов, Phuket Tennis Family вернёт оплату в полном размере.', payment_refund_note:'Если после оплаты вы не попадёте в сезон из-за ограниченного количества мест или распределения дивизионов, Phuket Tennis Family вернёт оплату в полном размере.',
    admin_only:'Эта команда доступна только администратору.', admin_help:`<b>PTF Admin Help</b>\n\n/admin_init — привязать текущий чат как админский inbox\n/stats — статистика\n/events — активные события\n/pending — новые заявки\n/messages — новые сообщения\n/profile @username или telegram_id — найти игрока\n/broadcast — создать рассылку\n/segments — сегменты рассылки\n/cancel — отменить действие\n\nОтвет игроку: нажмите Reply под сообщением игрока или ответьте reply на админское уведомление, где указан TGID.`, join_chat:'💬 Вступить в клубный чат',
    challenge_needs_profile:'<b>🎾 Чтобы вызвать игрока на матч, нужна анкета игрока.</b>\n\nВызовы доступны только участникам Phuket Tennis Family или игрокам с заполненным профилем. Заполните короткую анкету, и после этого сможете вызывать других игроков на матч.', challenge_self:'Вы не можете вызвать на матч самого себя.', challenge_target_missing:'Игрок не найден или у него нет Telegram-профиля в системе.', challenge_sent:'✅ Вызов отправлен игроку. Вы получите уведомление, когда он ответит.', challenge_received:'🎾 Игрок <b>{name}</b> вызывает вас на матч. Посмотрите профиль игрока и выберите действие.', challenge_accept:'✅ Принять', challenge_decline:'❌ Отклонить', challenge_profile:'👤 Профиль игрока', challenge_accepted_to_target:'✅ Вызов принят. Теперь вы можете договориться о времени матча напрямую.', challenge_accepted_to_from:'✅ Игрок <b>{name}</b> принял ваш вызов на матч.', challenge_declined_to_target:'Вызов отклонён.', challenge_declined_to_from:'❌ Игрок <b>{name}</b> отклонил ваш вызов на матч.', write_player:'💬 Написать игроку', fallback_chat_opened:'У одного из игроков нет публичного Telegram username, поэтому я открыл временный чат через бота. Напишите сообщение сюда, и я перешлю его игроку.', challenge_chat_closed:'Временный чат закрыт.'
  },
  en: {
    join:'🎾 Join', apply:'🎾 Join', website:'🌐 PTF Website', about:'ℹ️ About PTF', how:'🏆 How League Works', yearly:'⭐ Yearly Race', pass:'🎟 League Pass', contact:'💬 Contact', back:'⬅️ Back', main_menu:'🏠 Main Menu', close_chat:'❌ Close Chat',
    help_user:'<b>Help</b>\n\nUse the menu to join, open the website, learn how the league works or contact the organizer.',
    contact_prompt:'<b>💬 Organizer chat is open</b>\n\nWrite your question. All next messages will be sent to the organizer until you close the chat or return to the main menu.', contact_sent:'✅ Your message has been sent to the organizer. You can write another message here or close the chat.', contact_closed:'✅ Organizer chat closed.', cancelled:'Cancelled.',
    application_received:'<b>Application received!</b> 🎾\n\nNow choose your League Pass payment method. After payment, upload a confirmation screenshot.\n\nIf spots are not available or your division is not confirmed, Phuket Tennis Family will refund the full amount.',
    pay_later:'⏳ Pay later', bank:'🏦 Bank Transfer', crypto:'💵 USDT', call_admin:'💬 Contact organizer', choose_payment:'Choose payment method:', choose_crypto_network:'Choose USDT network:', payment_later:'Okay. You can pay later. The organizer can follow up on your application.', send_proof:'After payment, send the confirmation screenshot here.', proof_received:'✅ Payment screenshot received. The organizer will check it and confirm your participation status separately.',
    waitlist:'<b>You have been added to the waitlist.</b> ⏳\n\nWe are currently finalizing available spots and division lineups. Priority is given to players who already have experience in the Phuket Tennis Family system.\n\nWe will notify you as soon as your application status changes.', active:'<b>Congratulations!</b> 🎾\n\nYour participation has been confirmed.', refunded:'<b>Refund</b>\n\nIf you do not get a place in the season due to limited spots or division allocation, Phuket Tennis Family will refund the full amount.', payment_refund_note:'If after payment you do not get a place in the season due to limited spots or division allocation, Phuket Tennis Family will refund the full amount.',
    admin_only:'This command is available only to admins.', admin_help:`<b>PTF Admin Help</b>\n\n/admin_init — set current chat as admin inbox\n/stats — stats\n/events — active events\n/pending — pending applications\n/messages — new messages\n/profile @username or telegram_id — find player\n/broadcast — create broadcast\n/segments — broadcast segments\n/cancel — cancel current action\n\nReply to player: press Reply under the incoming message or reply to an admin notification containing TGID.`, join_chat:'💬 Join Club Chat',
    challenge_needs_profile:'<b>🎾 To challenge a player, you need a player profile.</b>\n\nChallenges are available only to Phuket Tennis Family participants or players with a completed profile. Complete a short form first, and then you will be able to challenge other players.', challenge_self:'You cannot challenge yourself.', challenge_target_missing:'Player not found or the player has no Telegram profile in the system.', challenge_sent:'✅ Challenge sent. You will be notified when the player responds.', challenge_received:'🎾 <b>{name}</b> has challenged you to a match. View the player profile and choose your response.', challenge_accept:'✅ Accept', challenge_decline:'❌ Decline', challenge_profile:'👤 Player Profile', challenge_accepted_to_target:'✅ Challenge accepted. You can now arrange the match time directly.', challenge_accepted_to_from:'✅ <b>{name}</b> accepted your match challenge.', challenge_declined_to_target:'Challenge declined.', challenge_declined_to_from:'❌ <b>{name}</b> declined your match challenge.', write_player:'💬 Message player', fallback_chat_opened:'One of the players does not have a public Telegram username, so I opened a temporary chat through the bot. Write a message here, and I will forward it to the player.', challenge_chat_closed:'Temporary chat closed.'
  }
};
export function t(lang, key) { return (T[lang] || T.en)[key] || T.en[key] || key; }
export function tt(lang, key, vars={}) { let s = t(lang, key); for (const [k,v] of Object.entries(vars)) s = s.replaceAll(`{${k}}`, String(v ?? '')); return s; }
