export const T = {
  ru: {
    join:'🎾 Заполнить анкету', join_event:'🏆 Участвовать в событии', participants:'👥 Список участников', apply:'🎾 Подать заявку', website:'ℹ️ О PTF', about:'ℹ️ О PTF', how:'🏆 Как работает лига', yearly:'⭐ Yearly Race', pass:'💳 Оплата', contact:'💬 Связаться', back:'⬅️ Назад', main_menu:'🏠 Главное меню', close_chat:'❌ Закрыть чат', choose_language:'<b>Выберите язык / Choose your language</b>\n\nПожалуйста, выберите язык для общения с ботом. Его можно будет изменить позднее через /language.', language_saved:'✅ Язык сохранён. Дальше бот будет общаться с вами на русском.',
    help_user:'<b>Помощь</b>\n\nИспользуйте меню, чтобы заполнить анкету игрока, податься в активное событие, открыть сайт, узнать как работает лига или связаться с организатором.',
    contact_prompt:'<b>💬 Чат с организатором открыт на 2 часа</b>\n\nПишите сюда как в обычный чат. Все сообщения будут передаваться организатору без дополнительных подтверждений после каждого сообщения.', contact_sent:'', contact_closed:'✅ Чат с организатором закрыт.', contact_expired:'⏱ Чат с организатором закрыт. Если хотите снова связаться, откройте чат через кнопку “Связаться”.', cancelled:'Отменено.',
    application_received:'<b>Заявка получена!</b> 🎾\n\nТеперь выберите способ оплаты League Pass. После оплаты загрузите скриншот подтверждения.\n\n⚠️ Неоплаченная заявка не является активным участием в сезоне. Заявки с подтверждённой оплатой будут рассматриваться в первую очередь.\n\nЕсли мест в сезоне не хватит или дивизион не будет подтверждён, Phuket Tennis Family вернёт оплату в полном размере.',
    pay_later:'⏳ Оплачу позже', bank:'🏦 Bank Transfer', crypto:'💵 USDT', call_admin:'💬 Связаться с организатором', choose_payment:'Выберите способ оплаты:', choose_crypto_network:'Выберите сеть USDT:', payment_later:'Окей. Вы можете оплатить позже. Организатор сможет сделать follow-up по вашей заявке.', send_proof:'После оплаты отправьте сюда скриншот подтверждения.', proof_received:'✅ Скриншот оплаты получен. Организатор проверит оплату и отдельно подтвердит ваш статус участия.', payment_section:'<b>💳 Оплата участия</b>\n\n<b>Что входит в стоимость</b>\n\n🏆 призовой фонд для каждого дивизиона\n🎾 аренда кортов для полуфиналов и финалов\n🎁 кубки, призы и подарки\n🔥 отчисления в призовой фонд Grand Final\n\n<b>Что оплачивается отдельно</b>\n\n— матчи регулярного сезона игроки организуют самостоятельно\n— аренда кортов на матчи регулярного сезона оплачивается за счёт игроков\n\n⚠️ Неоплаченная заявка не является активным участием. Заявки с подтверждённой оплатой будут рассматриваться в первую очередь.', payment_no_profile:'Чтобы перейти к оплате, сначала заполните анкету и выберите событие.', payment_no_application:'Анкета найдена. Чтобы выставить счёт, выберите открытое событие и отправьте заявку.', payment_already_proof:'Скриншот оплаты уже получен. Организатор проверит его вручную.', payment_already_paid:'Оплата уже подтверждена.', payment_active:'Ваше участие уже активно.', pay_now:'💳 Оплатить',
    waitlist:'<b>Вы добавлены в waitlist.</b> ⏳\n\nМы сейчас определяем доступные места и финальный состав дивизионов. Приоритет получают игроки, которые уже имеют опыт участия в системе Phuket Tennis Family.\n\nМы сообщим вам, как только статус заявки изменится.', active:'<b>Поздравляем!</b> 🎾\n\nВаше участие подтверждено.', refunded:'<b>Refund</b>\n\nЕсли вы не попали в сезон из-за ограниченного количества мест или распределения дивизионов, Phuket Tennis Family вернёт оплату в полном размере.', payment_refund_note:'Если после оплаты вы не попадёте в сезон из-за ограниченного количества мест или распределения дивизионов, Phuket Tennis Family вернёт оплату в полном размере.',
    admin_only:'Эта команда доступна только администратору.', admin_help:`<b>PTF Admin Help</b>\n\n/admin_init — привязать текущий чат как админский inbox\n/stats — статистика\n/events — активные события\n/pending — новые заявки\n/messages — новые сообщения\n/profile @username или telegram_id — найти игрока\n/broadcast — создать рассылку\n/broadcast_poll — разослать анонимный Telegram-опрос\n/broadcast_missing_rating — отправить просьбу указать NTRP (Raketo) тем, у кого рейтинг не заполнен\n/poll_stats poll_id — посмотреть результаты опроса\n/segments — сегменты рассылки\n/cancel — отменить действие\n\nОтвет игроку: нажмите Reply под сообщением игрока или ответьте reply на админское уведомление, где указан TGID.`, join_chat:'💬 Вступить в клубный чат',
    challenge_needs_profile:'<b>🎾 Чтобы вызвать игрока на матч, нужна анкета игрока.</b>\n\nВызовы доступны только участникам Phuket Tennis Family или игрокам с заполненным профилем. Заполните короткую анкету, и после этого сможете вызывать других игроков на матч.', challenge_self:'Вы не можете вызвать на матч самого себя.', challenge_target_missing:'Игрок не найден или у него нет Telegram-профиля в системе.', challenge_sent:'✅ Вызов отправлен игроку. Вы получите уведомление, когда он ответит.', challenge_received:'🎾 Игрок <b>{name}</b> вызывает вас на матч. Посмотрите профиль игрока и выберите действие.', challenge_accept:'✅ Принять', challenge_decline:'❌ Отклонить', challenge_profile:'👤 Профиль игрока', challenge_accepted_to_target:'✅ Вызов принят. Теперь вы можете договориться о времени матча напрямую.', challenge_accepted_to_from:'✅ Игрок <b>{name}</b> принял ваш вызов на матч.', challenge_declined_to_target:'Вызов отклонён.', challenge_declined_to_from:'❌ Игрок <b>{name}</b> отклонил ваш вызов на матч.', write_player:'💬 Написать игроку', fallback_chat_opened:'У одного из игроков нет публичного Telegram username, поэтому я открыл временный чат через бота. Напишите сообщение сюда, и я перешлю его игроку.', challenge_chat_closed:'Временный чат закрыт.', selfie_prompt:'<b>📸 Загрузка селфи</b>\n\nОтправьте сюда одно фото. Оно будет сохранено для аватарки и карточки игрока.', selfie_received:'✅ Селфи получено. Спасибо!'
  },
  en: {
    join:'🎾 Complete Profile', join_event:'🏆 Join Event', participants:'👥 Participants List', apply:'🎾 Join', website:'ℹ️ About PTF', about:'ℹ️ About PTF', how:'🏆 How League Works', yearly:'⭐ Yearly Race', pass:'💳 Payment', contact:'💬 Contact', back:'⬅️ Back', main_menu:'🏠 Main Menu', close_chat:'❌ Close Chat', choose_language:'<b>Choose your language / Выберите язык</b>\n\nPlease choose the language for bot communication. You can change it later with /language.', language_saved:'✅ Language saved. The bot will continue in English.',
    help_user:'<b>Help</b>\n\nUse the menu to complete your player profile, join an active event, open the website, learn how the league works or contact the organizer.',
    contact_prompt:'<b>💬 Organizer chat is open for 2 hours</b>\n\nWrite here as in a normal chat. All messages will be forwarded to the organizer without extra confirmation after each message.', contact_sent:'', contact_closed:'✅ Organizer chat closed.', contact_expired:'⏱ Organizer chat is closed. To contact us again, open it with the “Contact” button.', cancelled:'Cancelled.',
    application_received:'<b>Application received!</b> 🎾\n\nNow choose your League Pass payment method. After payment, upload a confirmation screenshot.\n\n⚠️ An unpaid application is not an active season entry. Applications with confirmed payment will be processed first.\n\nIf spots are not available or your division is not confirmed, Phuket Tennis Family will refund the full amount.',
    pay_later:'⏳ Pay later', bank:'🏦 Bank Transfer', crypto:'💵 USDT', call_admin:'💬 Contact organizer', choose_payment:'Choose payment method:', choose_crypto_network:'Choose USDT network:', payment_later:'Okay. You can pay later. The organizer can follow up on your application.', send_proof:'After payment, send the confirmation screenshot here.', proof_received:'✅ Payment screenshot received. The organizer will check it and confirm your participation status separately.', payment_section:'<b>💳 Participation payment</b>\n\n<b>What is included</b>\n\n🏆 prize fund for each division\n🎾 court rental for semifinals and finals\n🎁 trophies, prizes and gifts\n🔥 contribution to the Grand Final prize fund\n\n<b>Paid separately</b>\n\n— regular season matches are arranged by players independently\n— court rental for regular season matches is paid by players\n\n⚠️ An unpaid application is not an active entry. Applications with confirmed payment will be processed first.', payment_no_profile:'To proceed to payment, please complete your profile and choose an event first.', payment_no_application:'Profile found. To generate an invoice, choose an open event and submit your application.', payment_already_proof:'Payment screenshot has already been received. The organizer will review it manually.', payment_already_paid:'Payment is already confirmed.', payment_active:'Your participation is already active.', pay_now:'💳 Pay',
    waitlist:'<b>You have been added to the waitlist.</b> ⏳\n\nWe are currently finalizing available spots and division lineups. Priority is given to players who already have experience in the Phuket Tennis Family system.\n\nWe will notify you as soon as your application status changes.', active:'<b>Congratulations!</b> 🎾\n\nYour participation has been confirmed.', refunded:'<b>Refund</b>\n\nIf you do not get a place in the season due to limited spots or division allocation, Phuket Tennis Family will refund the full amount.', payment_refund_note:'If after payment you do not get a place in the season due to limited spots or division allocation, Phuket Tennis Family will refund the full amount.',
    admin_only:'This command is available only to admins.', admin_help:`<b>PTF Admin Help</b>\n\n/admin_init — set current chat as admin inbox\n/stats — stats\n/events — active events\n/pending — pending applications\n/messages — new messages\n/profile @username or telegram_id — find player\n/broadcast — create broadcast\n/broadcast_poll — send anonymous Telegram poll\n/broadcast_missing_rating — ask players with missing NTRP (Raketo) to update it\n/poll_stats poll_id — view poll results\n/segments — broadcast segments\n/cancel — cancel current action\n\nReply to player: press Reply under the incoming message or reply to an admin notification containing TGID.`, join_chat:'💬 Join Club Chat',
    challenge_needs_profile:'<b>🎾 To challenge a player, you need a player profile.</b>\n\nChallenges are available only to Phuket Tennis Family participants or players with a completed profile. Complete a short form first, and then you will be able to challenge other players.', challenge_self:'You cannot challenge yourself.', challenge_target_missing:'Player not found or the player has no Telegram profile in the system.', challenge_sent:'✅ Challenge sent. You will be notified when the player responds.', challenge_received:'🎾 <b>{name}</b> has challenged you to a match. View the player profile and choose your response.', challenge_accept:'✅ Accept', challenge_decline:'❌ Decline', challenge_profile:'👤 Player Profile', challenge_accepted_to_target:'✅ Challenge accepted. You can now arrange the match time directly.', challenge_accepted_to_from:'✅ <b>{name}</b> accepted your match challenge.', challenge_declined_to_target:'Challenge declined.', challenge_declined_to_from:'❌ <b>{name}</b> declined your match challenge.', write_player:'💬 Message player', fallback_chat_opened:'One of the players does not have a public Telegram username, so I opened a temporary chat through the bot. Write a message here, and I will forward it to the player.', challenge_chat_closed:'Temporary chat closed.', selfie_prompt:'<b>📸 Selfie upload</b>\n\nSend one photo here. It will be saved for your avatar and player profile card.', selfie_received:'✅ Selfie received. Thank you!'
  }
};
export function t(lang, key) { return (T[lang] || T.en)[key] || T.en[key] || key; }
export function tt(lang, key, vars={}) { let s = t(lang, key); for (const [k,v] of Object.entries(vars)) s = s.replaceAll(`{${k}}`, String(v ?? '')); return s; }
