import { inlineKeyboard, webAppButton, urlButton } from './telegram.js';
import { t } from './i18n.js';
import { getBotMenuRows } from './sheets.js';
export function mainKeyboard(lang) { return inlineKeyboard([[webAppButton(t(lang,'join'),'/apply?mode=profile')],[webAppButton(t(lang,'join_event'),'/apply?mode=event')],[{text:t(lang,'about'),callback_data:'website_menu'}],[{text:t(lang,'how'),callback_data:'text:how_league_works'}],[{text:t(lang,'yearly'),callback_data:'text:yearly_race'},{text:t(lang,'pass'),callback_data:'text:league_pass'}],[{text:t(lang,'contact'),callback_data:'contact'}]]); }
export function textKeyboard(lang,key) { const rows=[[webAppButton(t(lang,'join'),'/apply?mode=profile')],[webAppButton(t(lang,'join_event'),'/apply?mode=event')]]; if(key!=='how_league_works') rows.push([{text:t(lang,'how'),callback_data:'text:how_league_works'}]); if(key!=='yearly_race') rows.push([{text:t(lang,'yearly'),callback_data:'text:yearly_race'}]); if(key!=='yearly_race') rows.push([{text:t(lang,'about'),callback_data:'website_menu'}]); rows.push([{text:t(lang,'contact'),callback_data:'contact'},{text:t(lang,'back'),callback_data:'main'}]); return inlineKeyboard(rows); }
export function websiteKeyboard(lang, urls={}) { return inlineKeyboard([[{text:lang==='ru'?'🎾 Матчи':'🎾 Matches',url:urls.matches}],[{text:lang==='ru'?'🏆 Дивизионы':'🏆 Divisions',url:urls.divisions}],[{text:'⭐ Yearly Race',url:urls.yearlyRace}],[{text:lang==='ru'?'👥 Игроки':'👥 Players',url:urls.players}],[{text:t(lang,'back'),callback_data:'main'}]]); }
export function contactOpenKeyboard(lang) { return inlineKeyboard([[{text:t(lang,'main_menu'),callback_data:'main'},{text:t(lang,'close_chat'),callback_data:'close_contact'}]]); }
export function paymentKeyboard(lang, applicationId) { return inlineKeyboard([[{text:t(lang,'bank'),callback_data:`pay:${applicationId}:thai_bank`}],[{text:t(lang,'crypto'),callback_data:`crypto:${applicationId}`}],[{text:t(lang,'pay_later'),callback_data:`paylater:${applicationId}`}],[{text:t(lang,'call_admin'),callback_data:'contact'}]]); }
export function cryptoKeyboard(lang, applicationId) { return inlineKeyboard([[{text:'USDT BEP20',callback_data:`pay:${applicationId}:crypto_usdt_bep20`}],[{text:'USDT TRC20',callback_data:`pay:${applicationId}:crypto_usdt_trc20`}],[{text:'USDT ERC20',callback_data:`pay:${applicationId}:crypto_usdt_erc20`}],[{text:t(lang,'back'),callback_data:`payment_menu:${applicationId}`}]]); }
export function clubKeyboard(lang,url) { return inlineKeyboard([[urlButton(t(lang,'join_chat'),url)]]); }
export function challengeKeyboard(lang,challengeId,profileUrl) { const rows=[]; if(profileUrl) rows.push([{text:t(lang,'challenge_profile'),url:profileUrl}]); rows.push([{text:t(lang,'challenge_accept'),callback_data:`challenge_accept:${challengeId}`},{text:t(lang,'challenge_decline'),callback_data:`challenge_decline:${challengeId}`}]); return inlineKeyboard(rows); }
export function directChatKeyboard(lang,username) { return inlineKeyboard([[urlButton(t(lang,'write_player'),`https://t.me/${String(username||'').replace(/^@/,'')}`)]]); }
export function adminApplicationKeyboard(applicationId,telegramId) { return inlineKeyboard([[{text:'✅ Active',callback_data:`admin_status:${applicationId}:active`},{text:'⏳ Waitlist',callback_data:`admin_status:${applicationId}:waitlist`}],[{text:'❌ Rejected',callback_data:`admin_status:${applicationId}:rejected`},{text:'↩️ Refunded',callback_data:`admin_status:${applicationId}:refunded`}],[{text:'💬 Reply',callback_data:`admin_reply:${telegramId}`}]]); }
export function adminPaymentKeyboard(applicationId,paymentId,telegramId) { return inlineKeyboard([[{text:'✅ Approve payment',callback_data:`admin_payment:${applicationId}:${paymentId}:approved`},{text:'❌ Reject payment',callback_data:`admin_payment:${applicationId}:${paymentId}:rejected`}],[{text:'🎾 Set Active',callback_data:`admin_status:${applicationId}:active`},{text:'⏳ Set Waitlist',callback_data:`admin_status:${applicationId}:waitlist`}],[{text:'💬 Reply',callback_data:`admin_reply:${telegramId}`}]]); }

export function adminPanelKeyboard(lang) { return inlineKeyboard([[webAppButton('🛠 Open Admin Panel','/admin')]]); }

function mbtn(i){const t=i.label||i.menu_id;const type=String(i.action_type||'').toLowerCase();const v=i.action_value||'';if(type==='webapp'||type==='admin_webapp')return webAppButton(t,v);if(type==='url')return urlButton(t,v);if(type==='text')return {text:t,callback_data:`text:${v}`};if(type==='submenu')return {text:t,callback_data:`menu:${v}`};return {text:t,callback_data:v||'main'};}
export async function menuKeyboard(lang,parent='main',fallback=null){const rows=await getBotMenuRows(parent,lang);if(!rows.length)return fallback||mainKeyboard(lang);const map=new Map();for(const r of rows){const k=Number(r.row||1);if(!map.has(k))map.set(k,[]);map.get(k).push(r)}return inlineKeyboard([...map.entries()].sort((a,b)=>a[0]-b[0]).map(([,a])=>a.sort((x,y)=>Number(x.sort_order||999)-Number(y.sort_order||999)).map(mbtn)));}
