import { inlineKeyboard, webAppButton, urlButton } from './telegram.js';
import { t } from './i18n.js';
import { getBotMenuRows } from './sheets.js';
const DEFAULT_SITE_URL = 'https://phukettennis.com/';
function homeUrl(urls={}) { return urls.home || urls.website_url || DEFAULT_SITE_URL; }
function ratingButton(lang, urls={}) { return { text:t(lang,'rating'), url:homeUrl(urls) }; }
function contactButton(lang) { return { text:t(lang,'contact'), callback_data:'contact' }; }
function utilityRow(lang, urls={}) { return [contactButton(lang),ratingButton(lang, urls)]; }

export function mainKeyboard(lang, urls={}) { return inlineKeyboard([[webAppButton(t(lang,'join_event'),'/apply?mode=event')],[{text:t(lang,'about'),callback_data:'website_menu'},{text:t(lang,'how'),callback_data:'text:how_league_works'}],[{text:t(lang,'yearly'),callback_data:'text:yearly_race'},{text:t(lang,'pass'),callback_data:'text:league_pass'}],[ratingButton(lang, urls)],[contactButton(lang)]]); }
export function contactFallbackKeyboard(lang) { return inlineKeyboard([[contactButton(lang)],[{text:t(lang,'main_menu'),callback_data:'main'}]]); }
export function textKeyboard(lang,key,urls={}) { const rows=[[webAppButton(t(lang,'join_event'),'/apply?mode=event')]]; const nav=[]; if(key!=='how_league_works') nav.push({text:t(lang,'how'),callback_data:'text:how_league_works'}); if(key!=='yearly_race') nav.push({text:t(lang,'yearly'),callback_data:'text:yearly_race'}); if(nav.length) rows.push(nav); if(key!=='yearly_race') rows.push([{text:t(lang,'about'),callback_data:'website_menu'}]); rows.push(utilityRow(lang, urls)); rows.push([{text:t(lang,'back'),callback_data:'main'}]); return inlineKeyboard(rows); }
export function websiteKeyboard(lang, urls={}) { return inlineKeyboard([[{text:lang==='ru'?'🎾 Матчи':'🎾 Matches',url:urls.matches},{text:lang==='ru'?'🏆 Дивизионы':'🏆 Divisions',url:urls.divisions}],[{text:'⭐ Yearly Race',url:urls.yearlyRace},{text:lang==='ru'?'👥 Игроки':'👥 Players',url:urls.players}],utilityRow(lang, urls),[{text:t(lang,'back'),callback_data:'main'}]]); }
export function contactOpenKeyboard(lang, urls={}) { return inlineKeyboard([[{text:t(lang,'main_menu'),callback_data:'main'},{text:t(lang,'close_chat'),callback_data:'close_contact'}],[ratingButton(lang, urls)]]); }
export function paymentKeyboard(lang, applicationId, urls={}) { return inlineKeyboard([[{text:t(lang,'bank'),callback_data:`pay:${applicationId}:thai_bank`}],[{text:t(lang,'crypto'),callback_data:`crypto:${applicationId}`}],[{text:t(lang,'pay_later'),callback_data:`paylater:${applicationId}`}],utilityRow(lang, urls)]); }
export function cryptoKeyboard(lang, applicationId, urls={}) { return inlineKeyboard([[{text:'USDT BEP20',callback_data:`pay:${applicationId}:crypto_usdt_bep20`}],[{text:'USDT TRC20',callback_data:`pay:${applicationId}:crypto_usdt_trc20`}],[{text:'USDT ERC20',callback_data:`pay:${applicationId}:crypto_usdt_erc20`}],utilityRow(lang, urls),[{text:t(lang,'back'),callback_data:`payment_menu:${applicationId}`}]]); }
export function clubKeyboard(lang,url,urls={}) { return inlineKeyboard([[urlButton(t(lang,'join_chat'),url)],utilityRow(lang, urls)]); }
export function challengeKeyboard(lang,challengeId,profileUrl,urls={}) { const rows=[]; if(profileUrl) rows.push([{text:t(lang,'challenge_profile'),url:profileUrl}]); rows.push([{text:t(lang,'challenge_accept'),callback_data:`challenge_accept:${challengeId}`},{text:t(lang,'challenge_decline'),callback_data:`challenge_decline:${challengeId}`}]); rows.push(utilityRow(lang, urls)); return inlineKeyboard(rows); }
export function directChatKeyboard(lang,username,urls={}) { return inlineKeyboard([[urlButton(t(lang,'write_player'),`https://t.me/${String(username||'').replace(/^@/,'')}`)],utilityRow(lang, urls)]); }
export function adminApplicationKeyboard(applicationId,telegramId) { return inlineKeyboard([[{text:'✅ Active',callback_data:`admin_status:${applicationId}:active`},{text:'⏳ Waitlist',callback_data:`admin_status:${applicationId}:waitlist`}],[{text:'❌ Rejected',callback_data:`admin_status:${applicationId}:rejected`},{text:'↩️ Refunded',callback_data:`admin_status:${applicationId}:refunded`}],[{text:'💬 Reply',callback_data:`admin_reply:${telegramId}`}]]); }
export function adminPaymentKeyboard(applicationId,paymentId,telegramId) { return inlineKeyboard([[{text:'✅ Approve payment',callback_data:`admin_payment:${applicationId}:${paymentId}:approved`},{text:'❌ Reject payment',callback_data:`admin_payment:${applicationId}:${paymentId}:rejected`}],[{text:'🎾 Set Active',callback_data:`admin_status:${applicationId}:active`},{text:'⏳ Set Waitlist',callback_data:`admin_status:${applicationId}:waitlist`}],[{text:'💬 Reply',callback_data:`admin_reply:${telegramId}`}]]); }

export function adminPanelKeyboard(lang) { return inlineKeyboard([[webAppButton('🛠 Open Admin Panel','/admin')]]); }

function mbtn(i){const t=i.label||i.menu_id;const type=String(i.action_type||'').toLowerCase();const v=i.action_value||'';if(type==='webapp'||type==='admin_webapp')return webAppButton(t,v);if(type==='url')return urlButton(t,v);if(type==='text')return {text:t,callback_data:`text:${v}`};if(type==='submenu')return {text:t,callback_data:`menu:${v}`};return {text:t,callback_data:v||'main'};}
export async function menuKeyboard(lang,parent='main',fallback=null){const rows=await getBotMenuRows(parent,lang);if(!rows.length)return fallback||mainKeyboard(lang);const map=new Map();for(const r of rows){const k=Number(r.row||1);if(!map.has(k))map.set(k,[]);map.get(k).push(r)}const built=[...map.entries()].sort((a,b)=>a[0]-b[0]).map(([,a])=>a.sort((x,y)=>Number(x.sort_order||999)-Number(y.sort_order||999)).map(mbtn));built.push(utilityRow(lang));return inlineKeyboard(built);}
